name: Marte GitTea Deploy UniqueServer

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: UniqueServer/UniqueServer.csproj
  PUBLISH_DIR: publish_output
  DEPLOY_DIR: /var/www/xpemuniqueserver
  SERVICE_NAME: xpemuniqueserver.service

jobs:
  deploy:
    runs-on: local

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Deploy files
        run: |
          sudo rm -rf ${{ env.DEPLOY_DIR }}/*
          sudo cp -r ${{ env.PUBLISH_DIR }}/* ${{ env.DEPLOY_DIR }}/
          sudo chown -R xpemdev:xpemdev ${{ env.DEPLOY_DIR }}

      - name: Restart service
        run: |
          sudo systemctl restart ${{ env.SERVICE_NAME }}
          sudo systemctl status ${{ env.SERVICE_NAME }}
